### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by glsmith86** [ltsdw/gofile-downloader#30] opened 2024-08-31 20:01 UTC
After download the latest script, downloader doesn't start downloading.

aaa@aaa-Aspire-F5-771G:/media/d_drive/aaa$ gofile https://gofile.io/d/....
Starting, please wait...
aaa@aaa-Aspire-F5-771G:/media/d_drive/aaa$ 

Nothing happening after the running. "gofile" is a shell script for easier running.

**Comment by ltsdw** [comment] 2024-08-31 20:14
Sadly I can't reproduce on my end, is there a url which I can reproduce the issue?
Does it also happen if you run normally without using your script?

./gofile-downloader.py gofileurl

**Comment by glsmith86** [comment] 2024-08-31 20:21
> Sadly I can't reproduce on my end, is there a url which I can reproduce the issue? Does it also happen if you run normally without using your script?
> 
> ./gofile-downloader.py gofileurl

It happens when I run python ~/gofile-downloader.py https://xyz...

Downloader can't download my upload: https://gofile.io/d/cVQZtT

**Comment by ltsdw** [comment] 2024-08-31 20:34
Thank you for your report, should be fixed by https://github.com/ltsdw/gofile-downloader/commit/8e4f21e23e954985a63dce3bc991b6a9ee8ca0e6

**Closed by ltsdw** 2024-08-31 20:34 UTC
